### ISSUE TITLE
Language dynamique

### ISSUE THREAD

**Issue by alexylem** [Gilles76/jarvis-wikipedia#1]
2 suggestions:

* Utilise la langue définie par l'utilisateur dans Jarvis plutôt que de la redemander dans la config du plugin:

**functions.sh**
```shell
$jv_pg_wk_lang="$(tr '[:lower:]' '[:upper:]' <<< ${language:0:2})" # en_GB => en => EN
```

Plus d'info sur les variables Jarvis ici:
http://domotiquefacile.fr/jarvis/content/public-api-reference

* Pas besoin de checker la langue dans `functions.sh`, car il y a un `functions.sh` par langue

**fr/functions.sh**
```shell
echo "Je n'ai rien trouvé"
```

**en/functions.sh**
```shell
echo "I found nothing"
```

Je t'aurais bien fait un pull request avec ces modifs, mais c'est l'occasion pour toi de te familiariser avec les plugins dans l'espoir que tu en fasses d'autres 😉

**Comment by Gilles76** [comment]
Merci pour tes conseils. Je n'ai pas l'habitude de développer sous plusieurs langues ! D'où des erreurs de jeunesse.
Je veux bien profiter de tes remarques et conseils, par contre non pas de "pull request", il faut que tu te concentres sur beaucoup d'autres choses. Ton savoir sera mieux utilisé ailleurs.

Heu en fait, il faut non seulement que je me familiarise avec les plugins mais surtout avec git et github.
Pour le moment je m'en sors pas trop mal.

Et oui je compte faire d'autres plugins. ;0)

**Comment by Gilles76** [comment]
C'est fait, dis-moi si cela te convient. et je clos cette demande.

**Comment by alexylem** [comment]
C'est presque parfait. Il faut que le fichier `config.sh` soit absolument vide (la il y a un commentaire et un ligne vide) car sinon il va demander à l'utilisateur de le remplir. S'il est vide il ne demandera rien. Tu peux tester en l'installant toi même 😄

**Comment by Gilles76** [comment]
Voilà c'est fait.
 
Bon, ça m'a bien aidé à mettre un pied dans github et git. merci pour ton aide.

suivant ....
